@startuml
title Rule Engine

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container(api_gateway, "API Gateway", "Kotlin", "Маршрутизация запросов")
ContainerDb(postgres, "PostgreSQL", "", "Хранение правил")
Container(control_service, "Control Service", "Kotlin", "Выполнение команд")

Container_Boundary(rule_service_boundary, "Rule Engine") {
    Component(rule_grpc_api, "Rule gRPC API", "Kotlin", "Обработка gRPC запросов управления правилами")
    Component(rule_user_request_service, "User Request Service", "Kotlin", "Ручной запуск сценариев")
    Component(rule_executor, "Rule Executor", "Kotlin", "Выполнение правил")
    Component(rule_condition_evaluator, "Condition Evaluator", "Kotlin", "Оценка условий срабатывания")
    Component(rule_schedule_manager, "Schedule Manager", "Kotlin", "Управление расписаниями")
    Component(rule_repository, "Rule Repository", "Kotlin", "Доступ к правилам")
}

Rel(rule_grpc_api, rule_repository, "CRUD правил")
Rel(rule_schedule_manager, rule_condition_evaluator, "Проверка по расписанию")
Rel(rule_condition_evaluator, rule_executor, "Правило сработало")
Rel(rule_executor, control_service, "Выполнение действий", "gRPC")
Rel(rule_user_request_service, rule_executor, "Запуск сценария")
Rel(rule_repository, postgres, "SQL запросы", "TCP/SQL")

Rel(api_gateway, rule_user_request_service, "Запрос на выполнения сценария", "gRPC")
Rel(api_gateway, rule_grpc_api, "Управление правилами", "gRPC")

@enduml