@startuml
title Приложение "Тёплый дом" в архитектуре монолит

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Управляет отоплением через веб-интерфейс")
Person(specialist, "Специалист-инженер", "Подключает и настраивает систему для клиента")

System_Boundary(warmhouse, "Тёплый дом") {
    Container(webapp, "приложение Тёплый дом", "Web-приложение", "Управление отоплением и мониторинг данных температуры")
    ContainerDb(db, "PostgreSQL", "SQL", "Хранит информацию о пользователях, домах, устройствах, температуре")
}

System_Ext(sensors, "Датчики отопления", "external_system", "Собирают данные о температуре и передают их по запросу")
System_Ext(rel, "Реле отопления", "external_system", "Включают/отключают обогрев по запросу")

Rel(user, webapp, "Использует через веб-интерфейс", "HTTP")
Rel(specialist, webapp, "Подключает и настраивает систему")
Rel(webapp, db, "взаимодействие с информацией о пользователях, домах, устройствах, температуре", "SQL")
Rel(webapp, sensors, "Запрашивает данные", "Синхронно по запросу")
Rel(webapp, rel, "Управляет состоянием отопления", "Синхронно по запросу")

@enduml